name: continuous-integration-foo

on:
    push:
        branches:
            - master

jobs:
    build-and-test:
        runs-on:  ubuntu-latest
        steps:
            - uses: actions/checkout@v1

            - name: Set up JDK 1.8
              uses: actions/setup-java@v1
              with:
                  java-version: 1.8

            - name: Build with Gradle!
              working-directory: .
              run: ./gradlew build -x test

            - name: Run tests
              working-directory: .
              run: ./gradlew test

    integration-test:
      runs-on: ubuntu-latest
      needs: build-and-test # make sure unit test is runing  first
      steps:
        -uses: actions/checkout@v1
        # 1. Run docker compose (hint 'up')
        # 2. Run python action (search online) and install pytest + requests
        # 3. Run 'pytest'
        # 4. Purge docker compose (hint 'down')

        # Run the server
        - name: Run Docker Compose
          working-directory: .
          run: docker-compose up -d --build # runs it background.

        # Install system test dependencies
        - name: Install pytest and requests
          working-directory: .
          run: pip3 install -U pytest && pip3 install -U requests

        # Run the integration tests
        - name: Run system tests
          working-directory: .
          run: pytest

          # Bringing container down
        - name: Purge containers
          working-directory: .
          run: docker-compose down